### ISSUE TITLE
failed to run the sample code after installing neuropod

### ISSUE THREAD

**Issue by tonardo2015** [uber/neuropod#388]
I tried to install neuropod and have a try with the sample, but it failed with below error:
```
[root@kworker2 home]# python neuropod_test.py
Traceback (most recent call last):
  File "neuropod_test.py", line 7, in <module>
    with load_neuropod(ADDITION_MODEL_PATH) as neuropod:
NameError: name 'load_neuropod' is not defined
```
I suppose it is because neuropod is not imported, so I included it, however it failed as well.
```
[root@kworker2 home]# python neuropod_test.py
Traceback (most recent call last):
  File "neuropod_test.py", line 2, in <module>
    import neuropod
ImportError: No module named neuropod
```
Here is the code that I update to run the test:
```
[root@kworker2 home]# cat neuropod_test.py
import numpy as np
import neuropod
from neuropod import load_neuropod
#from neuropod.loader import load_neuropod

x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

with load_neuropod(ADDITION_MODEL_PATH) as neuropod:
  results = neuropod.infer({"x": x, "y": y})

  # array([6, 8, 10, 12])
  print results["out"]
```
I've already installed neuropod following https://neuropod.ai/installing/ 

Could you please share if there is anything I missed? How can I use neuropod correctly? Thanks a lot!

**Comment by tomzhang** [comment]
which version of python that you using for?

in my environment I using python 3.6.9 and there no problem with loading neuropod after installation.


(base) zhangmiengdeair:pythonproject zhangmingfeng$ python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import neuropod

**Comment by VivekPanyam** [comment]
The commented out line in your test program is the correct one (`from neuropod.loader import load_neuropod`)

Also it doesn't look like Neuropod is correctly installed in your environment as `import neuropod` should work.

What installation steps did you follow?

See below for a simple example:
```
$ pip install neuropod
[snip]
$ python
Python 2.7.17 (default, Mar 31 2020, 17:25:23)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from neuropod.loader import load_neuropod
>>>
$
```

**Comment by tonardo2015** [comment]
> The commented out line in your test program is the correct one (`from neuropod.loader import load_neuropod`)
> 
> Also it doesn't look like Neuropod is correctly installed in your environment as `import neuropod` should work.
> 
> What installation steps did you follow?
> 
> See below for a simple example:
> 
> ```
> $ pip install neuropod
> [snip]
> $ python
> Python 2.7.17 (default, Mar 31 2020, 17:25:23)
> [GCC 8.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from neuropod.loader import load_neuropod
> >>>
> $
> ```

Thanks @VivekPanyam for reply. I use Python 2.7.5 in CentOS 7.7.  
Below is my console output as you can see neuropod is installed. 

[root@kworker2 home]# cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

[root@kworker2 home]# python --version
Python 2.7.5

[root@kworker2 home]# pip install neuropod
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: neuropod in /usr/lib/python2.7/site-packages (0.0.1a0)

[root@kworker2 home]# pip list | grep neuropod
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
neuropod                               0.0.1a0
neuropod-backend-python-27             0.0.1a0
neuropod-backend-python-35             0.0.1a0
neuropod-backend-python-36             0.0.1a0
neuropod-backend-python-37             0.0.1a0
neuropod-backend-python-38             0.0.1a0
neuropod-backend-torchscript-1-1-0-cpu 0.0.1a0
neuropod-backend-torchscript-1-2-0-cpu 0.0.1a0
neuropod-backend-torchscript-1-3-0-cpu 0.0.1a0
neuropod-backend-torchscript-1-4-0-cpu 0.0.1a0

[root@kworker2 home]# python
Python 2.7.5 (default, Apr  2 2020, 13:16:51)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from neuropod.loader import load_neuropod
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ImportError: No module named neuropod.loader**
>>>

Any suggestion to workaround or fix this failure? Thanks a lot!

**Comment by tonardo2015** [comment]
> which version of python that you using for?
> 
> in my environment I using python 3.6.9 and there no problem with loading neuropod after installation.
> 
> (base) zhangmiengdeair:pythonproject zhangmingfeng$ python
> Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import neuropod

Thanks Tom for answering. I'm using Python 2.7.5. Not sure if this is the root cause of the failure. It seems you are using python provided by Anaconda. I will have a try with that.

**Comment by VivekPanyam** [comment]
```
neuropod                               0.0.1a0
```

This isn't an actual release of Neuropod (it was a placeholder package uploaded to pypi). Did you install after the public release of Neuropod?

You should have (at least) version `0.2.0`

You can do `pip install -U neuropod`

You'll also need to install the backends as specified in https://neuropod.ai/installing/ (with the `-f` in the `pip install` command)

**Comment by VivekPanyam** [comment]
@tonardo2015 I'm going to close this issue as the solution I posted above should work (and it's been 30 days with no activity). Feel free to reopen it if necessary.

Thanks!

**Comment by tonardo2015** [comment]
> @tonardo2015 I'm going to close this issue as the solution I posted above should work (and it's been 30 days with no activity). Feel free to reopen it if necessary.
> 
> Thanks!

@VivekPanyam Thanks for help! I tried with Python3, it works. Looks there is some compatibility with Python 2.7. However, my issue is addressed.
